/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ExamExamIdRouteImport } from './routes/exam/$examId'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses/$courseSlug'
import { Route as AdminExamsIndexRouteImport } from './routes/admin/exams/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminExamsAddRouteImport } from './routes/admin/exams/add'
import { Route as AdminExamsExamIdRouteImport } from './routes/admin/exams/$examId'
import { Route as AdminCoursesAddRouteImport } from './routes/admin/courses/add'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin/courses/$courseId'
import { Route as ExamExamIdResultsAttemptIdRouteImport } from './routes/exam/$examId/results/$attemptId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/$courseSlug',
  path: '/$courseSlug',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminExamsIndexRoute = AdminExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExamsAddRoute = AdminExamsAddRouteImport.update({
  id: '/exams/add',
  path: '/exams/add',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExamsExamIdRoute = AdminExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesAddRoute = AdminCoursesAddRouteImport.update({
  id: '/courses/add',
  path: '/courses/add',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ExamExamIdResultsAttemptIdRoute =
  ExamExamIdResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => ExamExamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/exam/$examId': typeof ExamExamIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/add': typeof AdminCoursesAddRoute
  '/admin/exams/$examId': typeof AdminExamsExamIdRoute
  '/admin/exams/add': typeof AdminExamsAddRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/exams/': typeof AdminExamsIndexRoute
  '/exam/$examId/results/$attemptId': typeof ExamExamIdResultsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/exam/$examId': typeof ExamExamIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/add': typeof AdminCoursesAddRoute
  '/admin/exams/$examId': typeof AdminExamsExamIdRoute
  '/admin/exams/add': typeof AdminExamsAddRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/exams': typeof AdminExamsIndexRoute
  '/exam/$examId/results/$attemptId': typeof ExamExamIdResultsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/exam/$examId': typeof ExamExamIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/add': typeof AdminCoursesAddRoute
  '/admin/exams/$examId': typeof AdminExamsExamIdRoute
  '/admin/exams/add': typeof AdminExamsAddRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/exams/': typeof AdminExamsIndexRoute
  '/exam/$examId/results/$attemptId': typeof ExamExamIdResultsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/courses/$courseSlug'
    | '/exam/$examId'
    | '/admin/'
    | '/admin/courses/$courseId'
    | '/admin/courses/add'
    | '/admin/exams/$examId'
    | '/admin/exams/add'
    | '/admin/courses/'
    | '/admin/exams/'
    | '/exam/$examId/results/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/courses/$courseSlug'
    | '/exam/$examId'
    | '/admin'
    | '/admin/courses/$courseId'
    | '/admin/courses/add'
    | '/admin/exams/$examId'
    | '/admin/exams/add'
    | '/admin/courses'
    | '/admin/exams'
    | '/exam/$examId/results/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/courses/$courseSlug'
    | '/exam/$examId'
    | '/admin/'
    | '/admin/courses/$courseId'
    | '/admin/courses/add'
    | '/admin/exams/$examId'
    | '/admin/exams/add'
    | '/admin/courses/'
    | '/admin/exams/'
    | '/exam/$examId/results/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ExamExamIdRoute: typeof ExamExamIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug': {
      id: '/courses/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/exams/': {
      id: '/admin/exams/'
      path: '/exams'
      fullPath: '/admin/exams/'
      preLoaderRoute: typeof AdminExamsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/exams/add': {
      id: '/admin/exams/add'
      path: '/exams/add'
      fullPath: '/admin/exams/add'
      preLoaderRoute: typeof AdminExamsAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/exams/$examId': {
      id: '/admin/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/admin/exams/$examId'
      preLoaderRoute: typeof AdminExamsExamIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses/add': {
      id: '/admin/courses/add'
      path: '/courses/add'
      fullPath: '/admin/courses/add'
      preLoaderRoute: typeof AdminCoursesAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/exam/$examId/results/$attemptId': {
      id: '/exam/$examId/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/exam/$examId/results/$attemptId'
      preLoaderRoute: typeof ExamExamIdResultsAttemptIdRouteImport
      parentRoute: typeof ExamExamIdRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
  AdminCoursesAddRoute: typeof AdminCoursesAddRoute
  AdminExamsExamIdRoute: typeof AdminExamsExamIdRoute
  AdminExamsAddRoute: typeof AdminExamsAddRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminExamsIndexRoute: typeof AdminExamsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
  AdminCoursesAddRoute: AdminCoursesAddRoute,
  AdminExamsExamIdRoute: AdminExamsExamIdRoute,
  AdminExamsAddRoute: AdminExamsAddRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminExamsIndexRoute: AdminExamsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseSlugRoute: CoursesCourseSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface ExamExamIdRouteChildren {
  ExamExamIdResultsAttemptIdRoute: typeof ExamExamIdResultsAttemptIdRoute
}

const ExamExamIdRouteChildren: ExamExamIdRouteChildren = {
  ExamExamIdResultsAttemptIdRoute: ExamExamIdResultsAttemptIdRoute,
}

const ExamExamIdRouteWithChildren = ExamExamIdRoute._addFileChildren(
  ExamExamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ExamExamIdRoute: ExamExamIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
